project:
  type: website
  preview: 
    port: 4003

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Manuscript"
        href: _manuscript/index.html

format:
  html:
    toc: true

bibliography:
  - ../research.bib