project:
  type: website
  render: 
    - "*.qmd"
  preview: 
    port: 4003

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Manuscript"
        href: _manuscript/index.html

format:
  html:
    comments:
      hypothesis: true
  # docx: default
  # jats: default

  # (other formats)
  # pdf: default


bibliography:
  - ../research.bib