project:
  type: manuscript
  render:
    - "!presentations/"

manuscript:
  article: index.qmd

format:
  agu-pdf:
    cite-method: natbib # biblatex is not supported
    keep-tex: true
    latex-clean: false

citation:
  container-title: "JGR: Space Physics"
