name: psp_alignment
channels:
  - conda-forge
dependencies:
  - jupyter
  - pydantic
  - polars
  - pyarrow
  - pytables # used in `pyspedas`
  - sunpy
  - hvplot
  - dcor
  - pip
  - pip:
    - pyspedas @ git+https://github.com/Beforerr/pyspedas.git
    - ../space-analysis.py
    - ../ids_finder
    - ../beforerr_dev