---
title: Evolution of solar wind discontinuities in the inner heliosphere
subtitle: PSP and Earth conjunctions and alignments
author:
  - name: Zijin Zhang
    email: zijin@ucla.edu
    orcid: 0000-0002-9968-067X
    affiliation: University of California, Los Angeles
    roles: writing
    corresponding: true
  - name: Anton V. Artemyev
    email: aartemyev@igpp.ucla.edu
    orcid: 0000-0001-8823-4474
    affiliation: University of California, Los Angeles
  - name: Vassilis Angelopoulos
    orcid: 0000-0001-7024-1561
    affiliation: University of California, Los Angeles
code-links:
  - repo
  - href: https://app.tana.inc?nodeid=PZ6j7iriic2l
    text: Tana
  - href: zotero://select/library/collections/L9JC7XAI
    text: Zotero
---

# Motivation

Studying the radial evolution of solar wind discontinuities from synergistic observations of PSP and Earth-orbiting missions (ARTEMIS, Wind) during aligned intervals.

- How does the discontinuities change with the radial distance from the Sun?

- How is solar wind discontinuities formed? What is the physical mechanisms?

  - Generated at or near the sun?

  - Locally generated in the interplanetary space by turbulence?

# Methods

## In-situ synergistic observations (Alignment)

**Similar** type of solar wind or **Same** solar solar wind

How to define alignment?

- Trajectory & Orbits (theory): ballistic approximation of Parker spiral

- Plasma properties (observation): 

  - Invariants: plasma composition, ionization states, mass flux $n u r^2$

  - Correlation: magnetic field / plasma velocity

- Simulation: Trace plasma parcels evolution

<!-- sensing solar wind emitted from the same region on the solar surface, with the caveat that dynamical processes at the chromosphere–corona interface have not dramatically altered the solar footpoint within the time corresponding to the radial propagation from the measurement of one spacecraft to that of the other. -->


# References

-   @velliUnderstandingOriginsHeliosphere2020

-   @artemyevDynamicsIntenseCurrents2018 examined the evolution of transient currents in the solar wind using a data set compiled from observations of the same solar wind ﬂow at Earth’s and Mars's orbits.

    ```         
    > we show that it consists of several processes: discontinuity thinning (decrease in thickness normalized by the ion inertial length), intensiﬁcation of currents normalized to the proton thermal current (i.e., the product of proton charge, density, and thermal velocity), and increase in the compressional component of magnetic ﬁeld variations across discontinuities.
    ```

## Anistropy

@shenComparingPlasmaAnisotropy2024

pressure anisotropy is defined as $Λ = \mu (P_∥ - P_⊥) / B^2$.