# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.2"
manifest_format = "2.0"
project_hash = "f38bcf793b4497750adccd2f35e7fd67cb7f95fc"

[[deps.Discontinuity]]
deps = ["LaTeXStrings"]
path = "/Users/zijin/.julia/dev/Discontinuity"
uuid = "b54b658d-ecbf-47cc-8c7f-673f5d2a4b30"
version = "1.0.0-DEV"

[[deps.LaTeXStrings]]
git-tree-sha1 = "50901ebc375ed41dbf8058da26f9de442febbbec"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.1"
