[project]
name = "psp_alignment"
version = "0.1.0"
description = "Add a short description here"
authors = ["Beforerr <zzj956959688@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "<3.11"
jupyter = "*"
pydantic = "*"
polars = "*"
pyarrow = "*"
pytables = "*"
sunpy = "*"
hvplot = "*"
dcor = "*"

[pypi-dependencies]
pyspedas = "*"
discontinuitypy = { path = "../ids_finder", editable = true}
beforerr = { path = "../beforerr_dev", editable = true}
space_analysis = { path = "../space-analysis.py", editable = true}